server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}
            
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
              
        - id: service-service
          uri: http://service-service:8083
          predicates:
            - Path=/api/services/**
          filters:
            - RewritePath=/api/services/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
              
        - id: rating-service
          uri: http://rating-service:8084
          predicates:
            - Path=/api/ratings/**
          filters:
            - RewritePath=/api/ratings/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
              
        - id: payment-service
          uri: http://payment-service:8085
          predicates:
            - Path=/api/payments/**
          filters:
            - RewritePath=/api/payments/(?<segment>.*), /${segment}
            - name: AuthenticationFilter
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://frontend:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            exposedHeaders:
              - "Authorization"

jwt:
  secret: mySecretKey123456789012345678901234567890

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: DEBUG 